--- #YAML:1.0
name:                Parse-Flash-Cookie
version:             0.03
abstract:            A flash cookie parser.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    File::Spec::Functions:         0
    Log::Log4perl:                 0
    Test::Differences:             0
    Test::More:                    0
    URI::Escape:                   0
    XML::Writer:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andreas Faafeng <aff@cpan.org>
